# security-tools/bandit-config.yml
# This profile will be used by Bandit for static code analysis.
# We are defining a baseline profile to fail on any issue found.

# A list of test IDs to skip, here we are not skipping any.
skips: []

# A list of paths to exclude from scanning.
exclude_dirs: ["./tests"]

# Fail the build if any issue with a severity of LOW or higher is found.
# Severities: LOW, MEDIUM, HIGH
level: "LOW"
confidence: "LOW"